// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: massa/model/v1/address.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address category discriminant
type AddressCategory int32

const (
	// Unspecified address category
	AddressCategory_ADDRESS_CATEGORY_UNSPECIFIED AddressCategory = 0
	// User address
	AddressCategory_ADDRESS_CATEGORY_USER_ADDRESS AddressCategory = 1
	// Smart contract address
	AddressCategory_ADDRESS_CATEGORY_SC_ADDRESS AddressCategory = 2
)

// Enum value maps for AddressCategory.
var (
	AddressCategory_name = map[int32]string{
		0: "ADDRESS_CATEGORY_UNSPECIFIED",
		1: "ADDRESS_CATEGORY_USER_ADDRESS",
		2: "ADDRESS_CATEGORY_SC_ADDRESS",
	}
	AddressCategory_value = map[string]int32{
		"ADDRESS_CATEGORY_UNSPECIFIED":  0,
		"ADDRESS_CATEGORY_USER_ADDRESS": 1,
		"ADDRESS_CATEGORY_SC_ADDRESS":   2,
	}
)

func (x AddressCategory) Enum() *AddressCategory {
	p := new(AddressCategory)
	*p = x
	return p
}

func (x AddressCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_massa_model_v1_address_proto_enumTypes[0].Descriptor()
}

func (AddressCategory) Type() protoreflect.EnumType {
	return &file_massa_model_v1_address_proto_enumTypes[0]
}

func (x AddressCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressCategory.Descriptor instead.
func (AddressCategory) EnumDescriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{0}
}

// Massa NativeAddress
type NativeAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address category
	Category AddressCategory `protobuf:"varint,1,opt,name=category,proto3,enum=massa.model.v1.AddressCategory" json:"category,omitempty"`
	// Address version
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Address content
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *NativeAddress) Reset() {
	*x = NativeAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NativeAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeAddress) ProtoMessage() {}

func (x *NativeAddress) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeAddress.ProtoReflect.Descriptor instead.
func (*NativeAddress) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{0}
}

func (x *NativeAddress) GetCategory() AddressCategory {
	if x != nil {
		return x.Category
	}
	return AddressCategory_ADDRESS_CATEGORY_UNSPECIFIED
}

func (x *NativeAddress) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NativeAddress) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Addresses holds addresses
type Addresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Addresses
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *Addresses) Reset() {
	*x = Addresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_address_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Addresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Addresses) ProtoMessage() {}

func (x *Addresses) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_address_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Addresses.ProtoReflect.Descriptor instead.
func (*Addresses) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_address_proto_rawDescGZIP(), []int{1}
}

func (x *Addresses) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_massa_model_v1_address_proto protoreflect.FileDescriptor

var file_massa_model_v1_address_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x80,
	0x01, 0x0a, 0x0d, 0x4e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x3b, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x29, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x2a, 0x77, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x20, 0x0a, 0x1c, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47,
	0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x5f, 0x43, 0x41, 0x54,
	0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45,
	0x53, 0x53, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x5f,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x43, 0x5f, 0x41, 0x44, 0x44, 0x52,
	0x45, 0x53, 0x53, 0x10, 0x02, 0x42, 0x9f, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61,
	0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x33,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x61, 0x74, 0x74,
	0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0xa2, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xaa, 0x02, 0x12, 0x43,
	0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76,
	0x31, 0xba, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xca, 0x02, 0x12, 0x43, 0x6f, 0x6d,
	0x5c, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x5c, 0x56, 0x31, 0xea,
	0x02, 0x15, 0x43, 0x6f, 0x6d, 0x3a, 0x3a, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x3a, 0x3a, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_massa_model_v1_address_proto_rawDescOnce sync.Once
	file_massa_model_v1_address_proto_rawDescData = file_massa_model_v1_address_proto_rawDesc
)

func file_massa_model_v1_address_proto_rawDescGZIP() []byte {
	file_massa_model_v1_address_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_massa_model_v1_address_proto_rawDescData)
	})
	return file_massa_model_v1_address_proto_rawDescData
}

var file_massa_model_v1_address_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_massa_model_v1_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_massa_model_v1_address_proto_goTypes = []interface{}{
	(AddressCategory)(0),  // 0: massa.model.v1.AddressCategory
	(*NativeAddress)(nil), // 1: massa.model.v1.NativeAddress
	(*Addresses)(nil),     // 2: massa.model.v1.Addresses
}
var file_massa_model_v1_address_proto_depIdxs = []int32{
	0, // 0: massa.model.v1.NativeAddress.category:type_name -> massa.model.v1.AddressCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_massa_model_v1_address_proto_init() }
func file_massa_model_v1_address_proto_init() {
	if File_massa_model_v1_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_massa_model_v1_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NativeAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_address_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Addresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_massa_model_v1_address_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_address_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_address_proto_depIdxs,
		EnumInfos:         file_massa_model_v1_address_proto_enumTypes,
		MessageInfos:      file_massa_model_v1_address_proto_msgTypes,
	}.Build()
	File_massa_model_v1_address_proto = out.File
	file_massa_model_v1_address_proto_rawDesc = nil
	file_massa_model_v1_address_proto_goTypes = nil
	file_massa_model_v1_address_proto_depIdxs = nil
}
