// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: massa/model/v1/datastore.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddressKeys holds a list of addresses - keys
type AddressKeysEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of address- key entries
	AddressKeyEntries []*AddressKeyEntry `protobuf:"bytes,1,rep,name=address_key_entries,json=addressKeyEntries,proto3" json:"address_key_entries,omitempty"`
}

func (x *AddressKeysEntries) Reset() {
	*x = AddressKeysEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_datastore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressKeysEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressKeysEntries) ProtoMessage() {}

func (x *AddressKeysEntries) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressKeysEntries.ProtoReflect.Descriptor instead.
func (*AddressKeysEntries) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{0}
}

func (x *AddressKeysEntries) GetAddressKeyEntries() []*AddressKeyEntry {
	if x != nil {
		return x.AddressKeyEntries
	}
	return nil
}

// AddressKeyEntry
type AddressKeyEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Associated address of the entry
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Datastore key
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AddressKeyEntry) Reset() {
	*x = AddressKeyEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_datastore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressKeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressKeyEntry) ProtoMessage() {}

func (x *AddressKeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressKeyEntry.ProtoReflect.Descriptor instead.
func (*AddressKeyEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{1}
}

func (x *AddressKeyEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressKeyEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// DatastoreEntry
type DatastoreEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// final datastore entry value
	FinalValue []byte `protobuf:"bytes,1,opt,name=final_value,json=finalValue,proto3" json:"final_value,omitempty"`
	// candidate_value datastore entry value
	CandidateValue []byte `protobuf:"bytes,2,opt,name=candidate_value,json=candidateValue,proto3" json:"candidate_value,omitempty"`
}

func (x *DatastoreEntry) Reset() {
	*x = DatastoreEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_datastore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatastoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatastoreEntry) ProtoMessage() {}

func (x *DatastoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_datastore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatastoreEntry.ProtoReflect.Descriptor instead.
func (*DatastoreEntry) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_datastore_proto_rawDescGZIP(), []int{2}
}

func (x *DatastoreEntry) GetFinalValue() []byte {
	if x != nil {
		return x.FinalValue
	}
	return nil
}

func (x *DatastoreEntry) GetCandidateValue() []byte {
	if x != nil {
		return x.CandidateValue
	}
	return nil
}

var File_massa_model_v1_datastore_proto protoreflect.FileDescriptor

var file_massa_model_v1_datastore_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31,
	0x22, 0x65, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x13, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x66,
	0x69, 0x6e, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x9f, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x61, 0x74, 0x74, 0x73, 0x2f, 0x67,
	0x6f, 0x2d, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d,
	0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0xa2, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xaa, 0x02, 0x12, 0x43, 0x6f, 0x6d, 0x2e,
	0x4d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0xba, 0x02,
	0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xca, 0x02, 0x12, 0x43, 0x6f, 0x6d, 0x5c, 0x4d, 0x61,
	0x73, 0x73, 0x61, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x5c, 0x56, 0x31, 0xea, 0x02, 0x15, 0x43,
	0x6f, 0x6d, 0x3a, 0x3a, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x3a, 0x3a, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_massa_model_v1_datastore_proto_rawDescOnce sync.Once
	file_massa_model_v1_datastore_proto_rawDescData = file_massa_model_v1_datastore_proto_rawDesc
)

func file_massa_model_v1_datastore_proto_rawDescGZIP() []byte {
	file_massa_model_v1_datastore_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_datastore_proto_rawDescData = protoimpl.X.CompressGZIP(file_massa_model_v1_datastore_proto_rawDescData)
	})
	return file_massa_model_v1_datastore_proto_rawDescData
}

var file_massa_model_v1_datastore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_massa_model_v1_datastore_proto_goTypes = []interface{}{
	(*AddressKeysEntries)(nil), // 0: massa.model.v1.AddressKeysEntries
	(*AddressKeyEntry)(nil),    // 1: massa.model.v1.AddressKeyEntry
	(*DatastoreEntry)(nil),     // 2: massa.model.v1.DatastoreEntry
}
var file_massa_model_v1_datastore_proto_depIdxs = []int32{
	1, // 0: massa.model.v1.AddressKeysEntries.address_key_entries:type_name -> massa.model.v1.AddressKeyEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_massa_model_v1_datastore_proto_init() }
func file_massa_model_v1_datastore_proto_init() {
	if File_massa_model_v1_datastore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_massa_model_v1_datastore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressKeysEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_datastore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressKeyEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_datastore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatastoreEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_massa_model_v1_datastore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_datastore_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_datastore_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_datastore_proto_msgTypes,
	}.Build()
	File_massa_model_v1_datastore_proto = out.File
	file_massa_model_v1_datastore_proto_rawDesc = nil
	file_massa_model_v1_datastore_proto_goTypes = nil
	file_massa_model_v1_datastore_proto_depIdxs = nil
}
