// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: massa/model/v1/denunciation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Index for Denunciations in collections (e.g. like a HashMap...)
type DenunciationIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DenunciationBlockHeader or DenunciationEndorsement
	//
	// Types that are assignable to Entry:
	//
	//	*DenunciationIndex_BlockHeader
	//	*DenunciationIndex_Endorsement
	Entry isDenunciationIndex_Entry `protobuf_oneof:"entry"`
}

func (x *DenunciationIndex) Reset() {
	*x = DenunciationIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_denunciation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenunciationIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationIndex) ProtoMessage() {}

func (x *DenunciationIndex) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationIndex.ProtoReflect.Descriptor instead.
func (*DenunciationIndex) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{0}
}

func (m *DenunciationIndex) GetEntry() isDenunciationIndex_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (x *DenunciationIndex) GetBlockHeader() *DenunciationBlockHeader {
	if x, ok := x.GetEntry().(*DenunciationIndex_BlockHeader); ok {
		return x.BlockHeader
	}
	return nil
}

func (x *DenunciationIndex) GetEndorsement() *DenunciationEndorsement {
	if x, ok := x.GetEntry().(*DenunciationIndex_Endorsement); ok {
		return x.Endorsement
	}
	return nil
}

type isDenunciationIndex_Entry interface {
	isDenunciationIndex_Entry()
}

type DenunciationIndex_BlockHeader struct {
	// Denunciation block header
	BlockHeader *DenunciationBlockHeader `protobuf:"bytes,1,opt,name=block_header,json=blockHeader,proto3,oneof"`
}

type DenunciationIndex_Endorsement struct {
	// Denunciation endorsement
	Endorsement *DenunciationEndorsement `protobuf:"bytes,2,opt,name=endorsement,proto3,oneof"`
}

func (*DenunciationIndex_BlockHeader) isDenunciationIndex_Entry() {}

func (*DenunciationIndex_Endorsement) isDenunciationIndex_Entry() {}

// Variant for Block header denunciation index
type DenunciationBlockHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Denounciation slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *DenunciationBlockHeader) Reset() {
	*x = DenunciationBlockHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_denunciation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenunciationBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationBlockHeader) ProtoMessage() {}

func (x *DenunciationBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationBlockHeader.ProtoReflect.Descriptor instead.
func (*DenunciationBlockHeader) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{1}
}

func (x *DenunciationBlockHeader) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

// Variant for Endorsement denunciation index
type DenunciationEndorsement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Denounciation slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Denounciation index
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *DenunciationEndorsement) Reset() {
	*x = DenunciationEndorsement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_denunciation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DenunciationEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenunciationEndorsement) ProtoMessage() {}

func (x *DenunciationEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_denunciation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenunciationEndorsement.ProtoReflect.Descriptor instead.
func (*DenunciationEndorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_denunciation_proto_rawDescGZIP(), []int{2}
}

func (x *DenunciationEndorsement) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *DenunciationEndorsement) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_massa_model_v1_denunciation_proto protoreflect.FileDescriptor

var file_massa_model_v1_denunciation_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x64, 0x65, 0x6e, 0x75, 0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x76, 0x31, 0x1a, 0x19, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7,
	0x01, 0x0a, 0x11, 0x44, 0x65, 0x6e, 0x75, 0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x4c, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x73,
	0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6e, 0x75,
	0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6e, 0x75, 0x6e, 0x63, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42,
	0x07, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x43, 0x0a, 0x17, 0x44, 0x65, 0x6e, 0x75,
	0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x59, 0x0a,
	0x17, 0x44, 0x65, 0x6e, 0x75, 0x6e, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64,
	0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x9f, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d,
	0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64,
	0x61, 0x74, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xaa,
	0x02, 0x12, 0x43, 0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x76, 0x31, 0xba, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xca, 0x02, 0x12,
	0x43, 0x6f, 0x6d, 0x5c, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x5c,
	0x56, 0x31, 0xea, 0x02, 0x15, 0x43, 0x6f, 0x6d, 0x3a, 0x3a, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x3a,
	0x3a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_massa_model_v1_denunciation_proto_rawDescOnce sync.Once
	file_massa_model_v1_denunciation_proto_rawDescData = file_massa_model_v1_denunciation_proto_rawDesc
)

func file_massa_model_v1_denunciation_proto_rawDescGZIP() []byte {
	file_massa_model_v1_denunciation_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_denunciation_proto_rawDescData = protoimpl.X.CompressGZIP(file_massa_model_v1_denunciation_proto_rawDescData)
	})
	return file_massa_model_v1_denunciation_proto_rawDescData
}

var file_massa_model_v1_denunciation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_massa_model_v1_denunciation_proto_goTypes = []interface{}{
	(*DenunciationIndex)(nil),       // 0: massa.model.v1.DenunciationIndex
	(*DenunciationBlockHeader)(nil), // 1: massa.model.v1.DenunciationBlockHeader
	(*DenunciationEndorsement)(nil), // 2: massa.model.v1.DenunciationEndorsement
	(*Slot)(nil),                    // 3: massa.model.v1.Slot
}
var file_massa_model_v1_denunciation_proto_depIdxs = []int32{
	1, // 0: massa.model.v1.DenunciationIndex.block_header:type_name -> massa.model.v1.DenunciationBlockHeader
	2, // 1: massa.model.v1.DenunciationIndex.endorsement:type_name -> massa.model.v1.DenunciationEndorsement
	3, // 2: massa.model.v1.DenunciationBlockHeader.slot:type_name -> massa.model.v1.Slot
	3, // 3: massa.model.v1.DenunciationEndorsement.slot:type_name -> massa.model.v1.Slot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_massa_model_v1_denunciation_proto_init() }
func file_massa_model_v1_denunciation_proto_init() {
	if File_massa_model_v1_denunciation_proto != nil {
		return
	}
	file_massa_model_v1_slot_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_massa_model_v1_denunciation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenunciationIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_denunciation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenunciationBlockHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_denunciation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DenunciationEndorsement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_massa_model_v1_denunciation_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DenunciationIndex_BlockHeader)(nil),
		(*DenunciationIndex_Endorsement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_massa_model_v1_denunciation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_denunciation_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_denunciation_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_denunciation_proto_msgTypes,
	}.Build()
	File_massa_model_v1_denunciation_proto = out.File
	file_massa_model_v1_denunciation_proto_rawDesc = nil
	file_massa_model_v1_denunciation_proto_goTypes = nil
	file_massa_model_v1_denunciation_proto_depIdxs = nil
}
