// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: massa/model/v1/endorsement.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An endorsement, as sent in the network
type Endorsement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Slot in which the endorsement can be included
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Endorsement index inside the including block
	Index uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// Hash of endorsed block
	// This is the parent in thread `self.slot.thread` of the block in which the endorsement is included
	EndorsedBlock string `protobuf:"bytes,3,opt,name=endorsed_block,json=endorsedBlock,proto3" json:"endorsed_block,omitempty"`
}

func (x *Endorsement) Reset() {
	*x = Endorsement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_endorsement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsement) ProtoMessage() {}

func (x *Endorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsement.ProtoReflect.Descriptor instead.
func (*Endorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{0}
}

func (x *Endorsement) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *Endorsement) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Endorsement) GetEndorsedBlock() string {
	if x != nil {
		return x.EndorsedBlock
	}
	return ""
}

// Signed endorsement
type SignedEndorsement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Endorsement
	Content *Endorsement `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// A cryptographically generated value using `serialized_data` and a public key.
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// The public-key component used in the generation of the signature
	ContentCreatorPubKey string `protobuf:"bytes,3,opt,name=content_creator_pub_key,json=contentCreatorPubKey,proto3" json:"content_creator_pub_key,omitempty"`
	// Derived from the same public key used to generate the signature
	ContentCreatorAddress string `protobuf:"bytes,4,opt,name=content_creator_address,json=contentCreatorAddress,proto3" json:"content_creator_address,omitempty"`
	// A secure hash of the non-malleable contents of a deterministic binary representation of the block header
	SecureHash string `protobuf:"bytes,5,opt,name=secure_hash,json=secureHash,proto3" json:"secure_hash,omitempty"`
	// The size of the serialized endorsement in bytes
	SerializedSize uint64 `protobuf:"varint,6,opt,name=serialized_size,json=serializedSize,proto3" json:"serialized_size,omitempty"`
}

func (x *SignedEndorsement) Reset() {
	*x = SignedEndorsement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_endorsement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedEndorsement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEndorsement) ProtoMessage() {}

func (x *SignedEndorsement) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEndorsement.ProtoReflect.Descriptor instead.
func (*SignedEndorsement) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{1}
}

func (x *SignedEndorsement) GetContent() *Endorsement {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SignedEndorsement) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SignedEndorsement) GetContentCreatorPubKey() string {
	if x != nil {
		return x.ContentCreatorPubKey
	}
	return ""
}

func (x *SignedEndorsement) GetContentCreatorAddress() string {
	if x != nil {
		return x.ContentCreatorAddress
	}
	return ""
}

func (x *SignedEndorsement) GetSecureHash() string {
	if x != nil {
		return x.SecureHash
	}
	return ""
}

func (x *SignedEndorsement) GetSerializedSize() uint64 {
	if x != nil {
		return x.SerializedSize
	}
	return 0
}

// EndorsementIds holds endorsements ids
type EndorsementIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Endorsements ids
	EndorsementIds []string `protobuf:"bytes,1,rep,name=endorsement_ids,json=endorsementIds,proto3" json:"endorsement_ids,omitempty"`
}

func (x *EndorsementIds) Reset() {
	*x = EndorsementIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_endorsement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementIds) ProtoMessage() {}

func (x *EndorsementIds) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementIds.ProtoReflect.Descriptor instead.
func (*EndorsementIds) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{2}
}

func (x *EndorsementIds) GetEndorsementIds() []string {
	if x != nil {
		return x.EndorsementIds
	}
	return nil
}

// A wrapper around an endorsement with its metadata
type EndorsementWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether the endorsement is still in pool
	InPool bool `protobuf:"varint,1,opt,name=in_pool,json=inPool,proto3" json:"in_pool,omitempty"`
	// The endorsement appears in `in_blocks`
	// If it appears in multiple blocks, these blocks are in different cliques
	InBlocks []string `protobuf:"bytes,2,rep,name=in_blocks,json=inBlocks,proto3" json:"in_blocks,omitempty"`
	// Whether the the endorsement is final (for example in a final block)
	IsFinal bool `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// The endorsement itself
	Endorsement *SignedEndorsement `protobuf:"bytes,4,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (x *EndorsementWrapper) Reset() {
	*x = EndorsementWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_endorsement_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementWrapper) ProtoMessage() {}

func (x *EndorsementWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementWrapper.ProtoReflect.Descriptor instead.
func (*EndorsementWrapper) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{3}
}

func (x *EndorsementWrapper) GetInPool() bool {
	if x != nil {
		return x.InPool
	}
	return false
}

func (x *EndorsementWrapper) GetInBlocks() []string {
	if x != nil {
		return x.InBlocks
	}
	return nil
}

func (x *EndorsementWrapper) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *EndorsementWrapper) GetEndorsement() *SignedEndorsement {
	if x != nil {
		return x.Endorsement
	}
	return nil
}

// Informations about an endorsement with its metadata
type EndorsementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The endorsement id
	EndorsementId string `protobuf:"bytes,1,opt,name=endorsement_id,json=endorsementId,proto3" json:"endorsement_id,omitempty"`
	// Whether the endorsement is still in pool
	InPool bool `protobuf:"varint,2,opt,name=in_pool,json=inPool,proto3" json:"in_pool,omitempty"`
	// The endorsement appears in `in_blocks`
	// If it appears in multiple blocks, these blocks are in different cliques
	InBlocks []string `protobuf:"bytes,3,rep,name=in_blocks,json=inBlocks,proto3" json:"in_blocks,omitempty"`
	// Whether the the endorsement is final (for example in a final block)
	IsFinal bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
}

func (x *EndorsementInfo) Reset() {
	*x = EndorsementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_endorsement_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndorsementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndorsementInfo) ProtoMessage() {}

func (x *EndorsementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_endorsement_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndorsementInfo.ProtoReflect.Descriptor instead.
func (*EndorsementInfo) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_endorsement_proto_rawDescGZIP(), []int{4}
}

func (x *EndorsementInfo) GetEndorsementId() string {
	if x != nil {
		return x.EndorsementId
	}
	return ""
}

func (x *EndorsementInfo) GetInPool() bool {
	if x != nil {
		return x.InPool
	}
	return false
}

func (x *EndorsementInfo) GetInBlocks() []string {
	if x != nil {
		return x.InBlocks
	}
	return nil
}

func (x *EndorsementInfo) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_massa_model_v1_endorsement_proto protoreflect.FileDescriptor

var file_massa_model_v1_endorsement_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x31, 0x1a, 0x19, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a,
	0x0b, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73,
	0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x22, 0xa1, 0x02, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x6e,
	0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x61, 0x73,
	0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x64, 0x6f,
	0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x35,
	0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x27,
	0x0a, 0x0f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x39, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0e, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x73, 0x22, 0xaa, 0x01, 0x0a, 0x12, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f,
	0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x50, 0x6f,
	0x6f, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x43, 0x0a, 0x0b, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x89, 0x01, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e,
	0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x42, 0x9f, 0x01, 0x0a, 0x12,
	0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x64, 0x61, 0x74, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x61, 0x73, 0x73, 0x61,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44,
	0x45, 0x4c, 0xaa, 0x02, 0x12, 0x43, 0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0xba, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c,
	0xca, 0x02, 0x12, 0x43, 0x6f, 0x6d, 0x5c, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x5c, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x5c, 0x56, 0x31, 0xea, 0x02, 0x15, 0x43, 0x6f, 0x6d, 0x3a, 0x3a, 0x4d, 0x61, 0x73,
	0x73, 0x61, 0x3a, 0x3a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_massa_model_v1_endorsement_proto_rawDescOnce sync.Once
	file_massa_model_v1_endorsement_proto_rawDescData = file_massa_model_v1_endorsement_proto_rawDesc
)

func file_massa_model_v1_endorsement_proto_rawDescGZIP() []byte {
	file_massa_model_v1_endorsement_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_endorsement_proto_rawDescData = protoimpl.X.CompressGZIP(file_massa_model_v1_endorsement_proto_rawDescData)
	})
	return file_massa_model_v1_endorsement_proto_rawDescData
}

var file_massa_model_v1_endorsement_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_massa_model_v1_endorsement_proto_goTypes = []interface{}{
	(*Endorsement)(nil),        // 0: massa.model.v1.Endorsement
	(*SignedEndorsement)(nil),  // 1: massa.model.v1.SignedEndorsement
	(*EndorsementIds)(nil),     // 2: massa.model.v1.EndorsementIds
	(*EndorsementWrapper)(nil), // 3: massa.model.v1.EndorsementWrapper
	(*EndorsementInfo)(nil),    // 4: massa.model.v1.EndorsementInfo
	(*Slot)(nil),               // 5: massa.model.v1.Slot
}
var file_massa_model_v1_endorsement_proto_depIdxs = []int32{
	5, // 0: massa.model.v1.Endorsement.slot:type_name -> massa.model.v1.Slot
	0, // 1: massa.model.v1.SignedEndorsement.content:type_name -> massa.model.v1.Endorsement
	1, // 2: massa.model.v1.EndorsementWrapper.endorsement:type_name -> massa.model.v1.SignedEndorsement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_massa_model_v1_endorsement_proto_init() }
func file_massa_model_v1_endorsement_proto_init() {
	if File_massa_model_v1_endorsement_proto != nil {
		return
	}
	file_massa_model_v1_slot_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_massa_model_v1_endorsement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endorsement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_endorsement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedEndorsement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_endorsement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_endorsement_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_endorsement_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndorsementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_massa_model_v1_endorsement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_endorsement_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_endorsement_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_endorsement_proto_msgTypes,
	}.Build()
	File_massa_model_v1_endorsement_proto = out.File
	file_massa_model_v1_endorsement_proto_rawDesc = nil
	file_massa_model_v1_endorsement_proto_goTypes = nil
	file_massa_model_v1_endorsement_proto_depIdxs = nil
}
