// Copyright (c) 2023 MASSA LABS <info@massa.net>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: massa/model/v1/slot.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// When an address is drawn to create an endorsement it is selected for a specific index
type IndexedSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Slot
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	// Endorsement index in the slot
	Index uint64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *IndexedSlot) Reset() {
	*x = IndexedSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_slot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexedSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedSlot) ProtoMessage() {}

func (x *IndexedSlot) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedSlot.ProtoReflect.Descriptor instead.
func (*IndexedSlot) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{0}
}

func (x *IndexedSlot) GetSlot() *Slot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *IndexedSlot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// A point in time where a block is expected
type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Period
	Period uint64 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	// Thread
	Thread uint32 `protobuf:"varint,2,opt,name=thread,proto3" json:"thread,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_slot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Slot) GetThread() uint32 {
	if x != nil {
		return x.Thread
	}
	return 0
}

// Slots
type Slots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Slots
	Slots []*Slot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
}

func (x *Slots) Reset() {
	*x = Slots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_slot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slots) ProtoMessage() {}

func (x *Slots) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slots.ProtoReflect.Descriptor instead.
func (*Slots) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{2}
}

func (x *Slots) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// SlotRange
type SlotRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Start lot (Optional)
	StartSlot *Slot `protobuf:"bytes,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty"`
	// End slot (Optional)
	EndSlot *Slot `protobuf:"bytes,2,opt,name=end_slot,json=endSlot,proto3" json:"end_slot,omitempty"`
}

func (x *SlotRange) Reset() {
	*x = SlotRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_massa_model_v1_slot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotRange) ProtoMessage() {}

func (x *SlotRange) ProtoReflect() protoreflect.Message {
	mi := &file_massa_model_v1_slot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotRange.ProtoReflect.Descriptor instead.
func (*SlotRange) Descriptor() ([]byte, []int) {
	return file_massa_model_v1_slot_proto_rawDescGZIP(), []int{3}
}

func (x *SlotRange) GetStartSlot() *Slot {
	if x != nil {
		return x.StartSlot
	}
	return nil
}

func (x *SlotRange) GetEndSlot() *Slot {
	if x != nil {
		return x.EndSlot
	}
	return nil
}

var File_massa_model_v1_slot_proto protoreflect.FileDescriptor

var file_massa_model_v1_slot_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d, 0x61, 0x73,
	0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x4d, 0x0a, 0x0b, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x36, 0x0a, 0x04, 0x53, 0x6c,
	0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x74, 0x68, 0x72, 0x65,
	0x61, 0x64, 0x22, 0x33, 0x0a, 0x05, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x73,
	0x6c, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73,
	0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x22, 0x71, 0x0a, 0x09, 0x53, 0x6c, 0x6f, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x6c,
	0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61,
	0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6c, 0x6f,
	0x74, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x53, 0x6c, 0x6f, 0x74, 0x42, 0x9f, 0x01, 0x0a, 0x12, 0x63,
	0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x64, 0x61, 0x74, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x61, 0x73, 0x73, 0x61, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45,
	0x4c, 0xaa, 0x02, 0x12, 0x43, 0x6f, 0x6d, 0x2e, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x76, 0x31, 0xba, 0x02, 0x06, 0x4d, 0x4d, 0x4f, 0x44, 0x45, 0x4c, 0xca,
	0x02, 0x12, 0x43, 0x6f, 0x6d, 0x5c, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x5c, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x5c, 0x56, 0x31, 0xea, 0x02, 0x15, 0x43, 0x6f, 0x6d, 0x3a, 0x3a, 0x4d, 0x61, 0x73, 0x73,
	0x61, 0x3a, 0x3a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_massa_model_v1_slot_proto_rawDescOnce sync.Once
	file_massa_model_v1_slot_proto_rawDescData = file_massa_model_v1_slot_proto_rawDesc
)

func file_massa_model_v1_slot_proto_rawDescGZIP() []byte {
	file_massa_model_v1_slot_proto_rawDescOnce.Do(func() {
		file_massa_model_v1_slot_proto_rawDescData = protoimpl.X.CompressGZIP(file_massa_model_v1_slot_proto_rawDescData)
	})
	return file_massa_model_v1_slot_proto_rawDescData
}

var file_massa_model_v1_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_massa_model_v1_slot_proto_goTypes = []interface{}{
	(*IndexedSlot)(nil), // 0: massa.model.v1.IndexedSlot
	(*Slot)(nil),        // 1: massa.model.v1.Slot
	(*Slots)(nil),       // 2: massa.model.v1.Slots
	(*SlotRange)(nil),   // 3: massa.model.v1.SlotRange
}
var file_massa_model_v1_slot_proto_depIdxs = []int32{
	1, // 0: massa.model.v1.IndexedSlot.slot:type_name -> massa.model.v1.Slot
	1, // 1: massa.model.v1.Slots.slots:type_name -> massa.model.v1.Slot
	1, // 2: massa.model.v1.SlotRange.start_slot:type_name -> massa.model.v1.Slot
	1, // 3: massa.model.v1.SlotRange.end_slot:type_name -> massa.model.v1.Slot
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_massa_model_v1_slot_proto_init() }
func file_massa_model_v1_slot_proto_init() {
	if File_massa_model_v1_slot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_massa_model_v1_slot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexedSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_slot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_slot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_massa_model_v1_slot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_massa_model_v1_slot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_massa_model_v1_slot_proto_goTypes,
		DependencyIndexes: file_massa_model_v1_slot_proto_depIdxs,
		MessageInfos:      file_massa_model_v1_slot_proto_msgTypes,
	}.Build()
	File_massa_model_v1_slot_proto = out.File
	file_massa_model_v1_slot_proto_rawDesc = nil
	file_massa_model_v1_slot_proto_goTypes = nil
	file_massa_model_v1_slot_proto_depIdxs = nil
}
